name: bookoverflow

services:
  # PHP
  php:
    image: php:8.1-apache
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/

#   # MariaDB
#   db:
#     image: mariadb:10.6.7
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: $[MYSQL_ROOT_PASSWORD]
#       MYSQL_DATABASE: $[MYSQL_DATABASE]
#     ports:
#       - "3306:3306"
#     volumes:
#       - data:/var/lib/mysql
#     networks:
#       - bookoverflow-mariadb-network

#   # PHPMyAdmin
#   phpmyadmin:
#     depends_on:
#       - db
#     image: phpmyadmin
#     restart: always
#     ports:
#       - "8080:80"
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: $[MYSQL_ROOT_PASSWORD]
#     networks:
#       - bookoverflow-phpmyadmin-network

# networks:
#   bookoverflow-mariadb-network:
#     driver: bridge
#   mysql-phpmyadmin:
#     driver: bridge