name: bookoverflow

services:
  php:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/
    networks:
      - bookoverflow-network

  db:
    image: mariadb:10.6.7
    restart: always
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookoverflow
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      #- ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    networks:
      - bookoverflow-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "2222:80"
    environment:
      PMA_HOST: db
      PMA_USER: test
      PMA_PASSWORD: test
    networks:
      - bookoverflow-network

networks:
  bookoverflow-network:
    driver: bridge