version: '3'	
name: bookoverflow
services:
  # MariaDB
  db:
    image: mariadb:10.6.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $[MYSQL_ROOT_PASSWORD]
      MYSQL_DATABASE: $[MYSQL_DATABASE]
    ports:
      - "3306:3306"
    networks:
      - bookoverflow-mariadb-network

  # PHPMyAdmin
  phpmyadmin:

    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $[MYSQL_ROOT_PASSWORD]
    networks:
      - bookoverflow-phpmyadmin-network

networks:
  bookoverflow-mariadb-network:
    driver: bridge
  mysql-phpmyadmin:
    driver: bridge
