INSERT INTO
    `Utente` (
        `email`,
        `password_hash`,
        `username`,
        `nome`,
        `cognome`,
        `provincia`,
        `comune`,
        `path_immagine`,
        `generi_preferiti`
    )
VALUES
    (
        'admin@admin.com',
        '$2y$10$5TzwqibmBWvYzA77fWKLMO9v3bEWSMNM7c0Cj0R2Y8J6JkYyEleZ2',
        'admin',
        'admin',
        'admin',
        '28',
        '28060',
        'https://fastly.picsum.photos/id/532/500/500.jpg?hmac=gX2RSOOXKSV31haNz1jMrPzXCsx0bVJ_YV3v5GyuyOU',
        NULL
    ),
    (
        'ciao@ciao.com',
        '$2y$10$yQZ9L01v3VG9zx9MBy1AAuINU3/7fmE51ces3ur5JAo2WYmyvzyhq',
        'ciao',
        'sddas',
        'fsfsdf',
        '65',
        '65113',
        'https://fastly.picsum.photos/id/1038/500/500.jpg?hmac=_DTXehSaqnPMQnDQmVv1aW82ZomX7YYymYT5OE4r4To',
        NULL
    );
